DROP DATABASE IF EXISTS sa_p2;
CREATE DATABASE IF NOT EXISTS sa_p2;

CREATE TABLE IF NOT EXISTS sa_p2.users (
	id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    username VARCHAR(16) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL
);