CREATE DATABASE IF NOT EXISTS sa_p2;

DROP TABLE IF EXISTS sa_p2.users;

CREATE TABLE IF NOT EXISTS sa_p2.users (
	id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    username VARCHAR(128) NOT NULL,
    password VARCHAR(128) NOT NULL
);